version: "3" # makes yml compatible w/ swarm mode
services:
  frontend:
    image: rochong/moshimoji-fe:mid-PR-11
    ports:
      - "80:4000" # ReactQL app currently configured to be served on p 4000
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.9"
          memory: 500M
      restart_policy:
        condition: on-failure
    networks:
      - moshimoji-net
networks:
  moshimoji-net:
