- name: Move current secrets to prev dir
  shell: (cd /home/docker/secrets/ && tar c .) | (cd /home/docker/prev-secrets/ && tar xf -) && rm -rf /home/docker/secrets

- name: Push secrets
  copy: src='~/projects/moshimoji/docker/secrets/{{ env }}' dest='/home/docker/'

- name: Rename secrets dir into desired name
  shell: mv '/home/docker/{{ env }}' /home/docker/secrets

- name: Strip any trailing new lines in secrets (assuming that they are undesired)
  shell: for file in /home/docker/secrets/*; do printf %s "$(cat $file)" > $file; done

- name: Compare previous with new secrets
  shell: diff -r /home/docker/secrets /home/docker/prev-secrets
  register: secrets_output
  failed_when: secrets_output.rc > 1

- debug: var=secrets_output.stdout_lines
