- name: "Backup data"
  hosts: localhost
  tasks:
    - name: "Dump data"
      shell: pg_dump -h localhost -U mmuser moshimoji > moshimoji.sql

- name: "Push local sql to destination swarm"
  import_playbook: db-push-local-sql.yml "{{ env }}"
  when: env=="prod"

- name: "Restore data"
  hosts: "{{ 'localhost' if env=='stage' else env + '-manager' }}"
  tasks:
    - name: "Apply sql"
      vars:
        DB_NAME:  "{{ lookup('file', '/home/rona/projects/moshimoji/docker/secrets/{{ env }}/DB_NAME').rstrip() }}"
        DB_USERNAME: "{{ lookup('file', '/home/rona/projects/moshimoji/docker/secrets/{{ env }}/DB_USERNAME').rstrip() }}"
        DB_PASSWORD: "{{ lookup('file', '/home/rona/projects/moshimoji/docker/secrets/{{ env }}/DB_PASSWORD').rstrip() }}"
        DB_ENDPOINT: "{{ lookup('file', '/home/rona/projects/moshimoji/docker/secrets/{{ env }}/DB_ENDPOINT').rstrip() }}"
        SQL_FILE: "{{ '/home/rona/projects/moshimoji/ansible/moshimoji.sql' if env=='stage' else '/home/docker/moshimoji.sql' }}"
      shell:
        "PGPASSWORD={{ DB_PASSWORD }} psql -h {{ DB_ENDPOINT }} -U {{ DB_USERNAME }} {{ DB_NAME }} < {{ SQL_FILE }}"
      register: psql_out

    - debug: var=psql_out.stdout_lines
