- name: "Play: run deploy"
  hosts: '{{ env }}-manager'
  tasks:

  - name: Re-deploy moshimoji stack
    shell: docker stack deploy -c '/home/docker/compose-stack-{{env}}.yml' moshimoji-stack

  - name: Check services
    shell: docker service ls
    register: out

  - debug: var=out.stdout_lines

- name: "Play: check whether to run db-migrate playbook"
  hosts: localhost
  vars_prompt:
    - name: "run_migrate_playbook"
      prompt: |
        run migrate playbook?
        NOTE: for safety we also require new_db to be passed as an extra-var in order to migrate prod.
        ENTER to continue, ^C to stop

- name: "Playbook: db-migrate"
  import_playbook: db-migrate.yml "{{ env }}" "{{ new_db if new_db is defined else ''}}"
  when:
    - env=='stage' or new_db is defined
